services: 
  postgres:
    image: postgres:17.4-bookworm
    restart: always
    ports:
      - 5432:5432
    container_name: "postgres"
    environment:
      POSTGRES_USER: sony
      POSTGRES_PASSWORD: secret 
      POSTGRES_DB: user
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - test_postgres:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sony -d user"]  
      interval: 10s  
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  test_postgres:

